### ISSUE TITLE
Rotation Gates

### ISSUE THREAD

**Issue by Zshan0** [MalhotraPulak/StarQ#10]
Apart from default fundamental gates, we require rotation gates and controlled rotation gates.

This will add more complexity to the circuit but will make the language more complete.

```
(rx 0.1 1) ;; applies X rotation of 0.1 angle on qubit 1
```

We can also have controlled rotation of the following sort:

```
(crx 0.1 0 1) ;; control qubit being 1 and the target bit being 0.
```

If time permits and the complexity does not grow too much, we can further have the following pattern:

```
(crx (0.1 0.2) 0 (1 2))
```

This will translate to the following circuit:
```
(crx 0.1 0 1)
(crx 0.2 0 2)
```

The "zip" functionality already exists, the difference being that the gate will now take argument that will behave very similar to qubit arguments

**Comment by PulakIIIT** [comment]
Can you give some cQASM syntax examples too. I don't find any on their website: https://www.quantum-inspire.com/kbase/cr-gate/ @Zshan0

**Comment by Zshan0** [comment]
## Rotation Gates

There are three single qubit rotation gates [rx](https://www.quantum-inspire.com/kbase/rx-gate/), [ry](https://www.quantum-inspire.com/kbase/ry-gate/), [rz](https://www.quantum-inspire.com/kbase/rz-gate/). The links contain the examples for the same.

## Single Qubit Rotation

```
version 1.0
qubits 2
Rx q[0],-1.12  # the angle argument is given as the last argument
```

## Multi Qubit Rotation
cQASM has two parameter based multi-qubit rotation that is sufficient to construct all possible multi-qubit rotation gates. By default the pattern of the angle argument being the last argument follows.

```
version 1.0
qubits 2
CR q[0], q[1] -1.12  # q[0] is the control with q[1] as target and the angle being -1.12
```
