### ISSUE TITLE
Default for Two qubit gate

### ISSUE THREAD

**Issue by MalhotraPulak** [MalhotraPulak/StarQ#7]
When defining `CNOT` the default is unclear. This means we need to come up with a default.

`CNOT 0` -> `CNOT 0 x` for all x != 0 in circuit
`CNOT` -> `CNOT 0 1` `CNOT 1 2` ... in circuit

Come up with better default if necessary

**Comment by PulakIIIT** [comment]
if user gives n - 1 args to a gate with n qubits then last arg is all qubits
